# Generated by Django 3.2 on 2021-04-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_description',
            new_name='service_desc',
        ),
    ]
