# Generated by Django 3.2 on 2021-04-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_rename_service_description_services_service_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
